// Code generated by goyacc -o paser.y.go -v parser.y.output parser.y. DO NOT EDIT.

//line parser.y:2
package main

import __yyfmt__ "fmt"

//line parser.y:2

//line parser.y:5
type yySymType struct {
	yys          int
	num          int
	str          string
	indent_level int
}

const NR = 57346
const EOF = 57347
const COMMENT = 57348
const BOOL = 57349
const NUMBER = 57350
const STRING = 57351
const IDENT = 57352
const DEF = 57353
const NEW = 57354
const ANY = 57355
const NONE = 57356
const SH = 57357
const ECHO = 57358
const AGENT = 57359
const LABEL = 57360
const STAGE = 57361
const NODE = 57362
const DIR = 57363
const SCRIPT = 57364
const ENVIRONMENT = 57365
const IMPORT = 57366
const IF = 57367
const ELSE = 57368
const FOR = 57369
const IN = 57370
const TRY = 57371
const CATCH = 57372
const INCREMENT = 57373
const DECREMENT = 57374
const ARROW = 57375
const OR = 57376
const AND = 57377
const EQ = 57378
const NE = 57379
const LE = 57380
const GE = 57381
const UNARY_OPERAND = 57382

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NR",
	"EOF",
	"COMMENT",
	"BOOL",
	"NUMBER",
	"STRING",
	"IDENT",
	"DEF",
	"NEW",
	"ANY",
	"NONE",
	"SH",
	"ECHO",
	"AGENT",
	"LABEL",
	"STAGE",
	"NODE",
	"DIR",
	"SCRIPT",
	"ENVIRONMENT",
	"IMPORT",
	"IF",
	"ELSE",
	"FOR",
	"IN",
	"TRY",
	"CATCH",
	"INCREMENT",
	"DECREMENT",
	"ARROW",
	"OR",
	"AND",
	"'<'",
	"'>'",
	"EQ",
	"NE",
	"LE",
	"GE",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"UNARY_OPERAND",
	"'['",
	"']'",
	"'('",
	"')'",
	"'.'",
	"';'",
	"'='",
	"'{'",
	"'}'",
	"','",
	"':'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:189

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 52,
	1, 23,
	4, 23,
	5, 23,
	56, 23,
	-2, 104,
	-1, 72,
	56, 5,
	-2, 67,
	-1, 116,
	56, 5,
	-2, 67,
	-1, 117,
	33, 68,
	57, 68,
	-2, 45,
	-1, 137,
	4, 9,
	49, 9,
	-2, 75,
	-1, 145,
	4, 9,
	51, 9,
	-2, 75,
	-1, 149,
	4, 9,
	51, 9,
	-2, 75,
	-1, 156,
	56, 5,
	-2, 67,
	-1, 226,
	4, 9,
	51, 9,
	-2, 75,
}

const yyPrivate = 57344

const yyLast = 939

var yyAct = [...]int{

	138, 5, 29, 116, 5, 20, 118, 115, 53, 63,
	65, 66, 32, 114, 73, 123, 56, 71, 72, 70,
	74, 71, 80, 83, 1, 85, 172, 180, 31, 171,
	178, 5, 155, 57, 58, 153, 88, 72, 130, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 109, 172, 61, 86, 106, 108, 76, 54,
	56, 194, 5, 61, 228, 83, 67, 68, 72, 25,
	105, 69, 113, 117, 104, 77, 131, 132, 127, 133,
	87, 135, 18, 251, 18, 18, 111, 137, 139, 41,
	40, 42, 43, 44, 36, 145, 37, 36, 25, 37,
	143, 229, 170, 202, 168, 146, 57, 58, 61, 142,
	25, 110, 18, 149, 25, 25, 244, 117, 154, 156,
	78, 163, 165, 166, 159, 109, 25, 162, 25, 195,
	157, 173, 169, 56, 42, 43, 44, 177, 25, 75,
	36, 25, 37, 18, 182, 25, 25, 128, 28, 26,
	27, 59, 25, 23, 129, 213, 60, 117, 190, 193,
	136, 238, 236, 62, 167, 196, 81, 82, 144, 117,
	192, 203, 25, 222, 198, 220, 201, 248, 79, 33,
	206, 89, 242, 199, 24, 219, 150, 160, 217, 21,
	233, 22, 90, 216, 84, 223, 224, 129, 129, 214,
	107, 163, 51, 226, 25, 117, 232, 162, 187, 112,
	140, 232, 231, 34, 19, 177, 2, 211, 25, 17,
	3, 25, 62, 30, 0, 134, 186, 140, 240, 241,
	150, 0, 239, 0, 207, 208, 209, 243, 129, 62,
	0, 0, 0, 0, 0, 0, 0, 0, 250, 234,
	147, 0, 0, 249, 151, 152, 0, 0, 253, 254,
	0, 0, 215, 49, 38, 39, 45, 46, 48, 47,
	41, 40, 42, 43, 44, 0, 150, 0, 36, 237,
	37, 179, 181, 28, 26, 27, 59, 183, 23, 184,
	185, 60, 0, 0, 188, 189, 245, 0, 62, 191,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 197,
	0, 0, 0, 0, 0, 0, 204, 205, 0, 24,
	0, 0, 0, 210, 21, 212, 22, 0, 0, 0,
	0, 218, 0, 25, 0, 221, 28, 26, 27, 120,
	119, 23, 0, 0, 122, 121, 0, 0, 0, 0,
	126, 62, 0, 0, 130, 0, 124, 0, 125, 0,
	235, 0, 0, 25, 0, 0, 28, 26, 27, 59,
	0, 23, 24, 0, 60, 0, 0, 21, 0, 22,
	0, 62, 128, 25, 72, 0, 28, 26, 27, 120,
	119, 23, 0, 0, 122, 121, 0, 0, 0, 0,
	126, 62, 24, 0, 130, 0, 124, 21, 125, 22,
	0, 28, 26, 27, 161, 0, 23, 0, 0, 60,
	0, 0, 24, 0, 0, 0, 62, 21, 0, 22,
	0, 0, 227, 0, 72, 57, 58, 0, 0, 0,
	0, 0, 0, 28, 26, 27, 59, 24, 23, 0,
	0, 60, 21, 0, 164, 0, 0, 0, 62, 72,
	0, 0, 56, 28, 26, 27, 200, 119, 23, 0,
	0, 122, 121, 0, 0, 0, 0, 126, 62, 24,
	0, 130, 0, 124, 21, 125, 64, 0, 28, 26,
	27, 161, 0, 23, 0, 0, 60, 0, 0, 24,
	0, 0, 0, 62, 21, 0, 22, 0, 0, 0,
	0, 72, 57, 58, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 24, 0, 0, 0, 0, 21,
	0, 164, 0, 0, 0, 0, 72, 0, 0, 56,
	50, 49, 38, 39, 45, 46, 48, 47, 41, 40,
	42, 43, 44, 0, 0, 0, 36, 0, 37, 0,
	158, 72, 28, 26, 52, 59, 0, 23, 0, 0,
	60, 0, 0, 0, 0, 0, 0, 62, 0, 0,
	0, 0, 0, 0, 0, 0, 57, 58, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 24, 0,
	0, 0, 0, 21, 0, 55, 0, 0, 0, 0,
	61, 0, 0, 56, 50, 49, 38, 39, 45, 46,
	48, 47, 41, 40, 42, 43, 44, 0, 0, 0,
	36, 0, 37, 25, 17, 72, 28, 26, 27, 7,
	6, 23, 0, 0, 8, 9, 11, 10, 14, 15,
	16, 12, 13, 4, 0, 50, 49, 38, 39, 45,
	46, 48, 47, 41, 40, 42, 43, 44, 0, 0,
	0, 36, 24, 37, 0, 35, 0, 21, 0, 22,
	50, 49, 38, 39, 45, 46, 48, 47, 41, 40,
	42, 43, 44, 0, 0, 0, 36, 0, 37, 247,
	50, 49, 38, 39, 45, 46, 48, 47, 41, 40,
	42, 43, 44, 0, 0, 0, 36, 252, 37, 50,
	49, 38, 39, 45, 46, 48, 47, 41, 40, 42,
	43, 44, 0, 0, 0, 36, 246, 37, 50, 49,
	38, 39, 45, 46, 48, 47, 41, 40, 42, 43,
	44, 0, 0, 0, 36, 230, 37, 50, 49, 38,
	39, 45, 46, 48, 47, 41, 40, 42, 43, 44,
	0, 0, 0, 36, 225, 37, 50, 49, 38, 39,
	45, 46, 48, 47, 41, 40, 42, 43, 44, 0,
	0, 0, 36, 176, 37, 50, 49, 38, 39, 45,
	46, 48, 47, 41, 40, 42, 43, 44, 0, 0,
	0, 36, 175, 37, 50, 49, 38, 39, 45, 46,
	48, 47, 41, 40, 42, 43, 44, 0, 0, 0,
	36, 174, 37, 50, 49, 38, 39, 45, 46, 48,
	47, 41, 40, 42, 43, 44, 0, 0, 0, 36,
	148, 37, 50, 49, 38, 39, 45, 46, 48, 47,
	41, 40, 42, 43, 44, 0, 0, 0, 36, 141,
	37, 50, 49, 38, 39, 45, 46, 48, 47, 41,
	40, 42, 43, 44, 0, 0, 0, 36, 0, 37,
	28, 26, 27, 59, 0, 23, 0, 0, 60, 0,
	0, 0, 0, 0, 0, 62, 38, 39, 45, 46,
	48, 47, 41, 40, 42, 43, 44, 0, 0, 0,
	36, 0, 37, 0, 0, 0, 24, 0, 0, 0,
	0, 21, 0, 22, 0, 0, 0, 0, 72,
}
var yyPact = [...]int{

	629, -1000, 214, 629, 169, 621, 192, 555, 436, 276,
	276, 53, -37, 883, 89, 8, 70, -1000, 174, -1000,
	-35, -1000, 276, 184, 276, -1000, -1000, -1000, -1000, -1000,
	629, -1000, -1000, 28, -1000, 276, -1000, 182, 276, 276,
	276, 276, 276, 276, 276, 276, 276, 276, 276, 276,
	276, 20, -1000, 837, -1000, 276, 276, -1000, -1000, 2,
	61, 629, -41, 837, 276, 837, 837, -1000, -1000, -1000,
	-1000, 276, 329, 837, -1000, 276, 276, -1000, 276, -1000,
	-1000, 359, 217, 818, 59, 44, -1000, 169, 837, 359,
	-1000, 47, 47, 90, 90, 44, 44, 44, 47, 47,
	47, 47, 870, 228, 276, -1000, 799, 359, 837, -1000,
	-1000, -21, 217, 837, -24, 94, 329, 506, -1000, 177,
	481, 276, 436, 138, 54, -18, 52, -4, -1000, 174,
	276, 780, 761, 742, 217, 174, -27, -30, 837, -35,
	-42, -1000, -1000, -1000, -31, -35, 837, 359, -1, -35,
	-31, 359, 217, -1000, -35, -1000, 329, -1000, 276, -1000,
	7, 75, -1000, 837, 276, 837, 837, 13, 456, 73,
	276, -1000, -1000, 580, -1, -1, -1, -1000, -1000, 168,
	-1000, 106, 148, 359, 142, 137, -31, -1000, 134, 124,
	-35, 122, -1000, 837, 276, 276, 723, 359, -1000, 138,
	404, 11, 51, 704, 379, 359, -1000, -1000, -1000, -1000,
	141, -1000, 200, -1000, -1000, -31, -1000, -1000, 111, -1,
	-1000, 110, -1000, 837, 837, -18, -35, 276, 276, 172,
	-18, -1000, 837, -1000, -1000, 65, -1, -1000, -1000, -1000,
	685, 646, 167, -1000, -1000, -1000, -18, 276, 32, -1000,
	666, -18, -18, -1000, -1000,
}
var yyPgo = [...]int{

	0, 24, 216, 220, 13, 7, 3, 144, 81, 12,
	0, 78, 59, 6, 5, 15, 2, 214,
}
var yyR1 = [...]int{

	0, 1, 1, 1, 1, 4, 4, 4, 4, 7,
	7, 8, 8, 6, 6, 3, 3, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 12, 15, 15, 15, 5, 5, 5, 5, 5,
	5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
	5, 5, 5, 13, 9, 9, 9, 11, 11, 11,
	14, 14, 16, 16, 10, 10, 10, 10, 10, 10,
	10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
	10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
	10, 10, 10, 17, 17, 17, 17, 17,
}
var yyR2 = [...]int{

	0, 0, 1, 3, 2, 0, 1, 3, 2, 0,
	2, 1, 2, 1, 1, 1, 1, 2, 1, 2,
	4, 8, 3, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 5, 5, 2, 5, 5,
	7, 3, 3, 3, 3, 1, 1, 2, 4, 4,
	3, 2, 2, 2, 2, 1, 7, 9, 8, 5,
	5, 4, 2, 3, 1, 1, 3, 0, 1, 4,
	1, 4, 3, 3, 1, 1, 5, 6, 5, 6,
	6, 6, 6, 6, 5, 3, 7, 2, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 2, 2, 1, 1, 1, 1, 3,
}
var yyChk = [...]int{

	-1000, -1, -2, -3, 24, -10, 11, 10, 15, 16,
	18, 17, 22, 23, 19, 20, 21, 5, -8, -17,
	-14, 48, 50, 12, 43, 4, 8, 9, 7, -16,
	-3, -1, -9, 10, 44, 54, 50, 52, 36, 37,
	43, 42, 44, 45, 46, 38, 39, 41, 40, 35,
	34, 10, 9, -10, -12, 50, 58, 31, 32, 10,
	15, 55, 22, -10, 50, -10, -10, 13, 14, -12,
	-13, 58, 55, -10, -13, 50, 50, -12, 50, 4,
	57, -7, -7, -10, 10, -10, -1, 52, -10, -7,
	10, -10, -10, -10, -10, -10, -10, -10, -10, -10,
	-10, -10, -10, -10, 54, 50, -10, -7, -10, 50,
	50, -1, -7, -10, -4, -5, -6, -10, -13, 11,
	10, 16, 15, -15, 27, 29, 21, -11, 53, -8,
	25, -10, -10, -10, -7, -8, -11, -14, -10, -14,
	10, 51, 50, -9, -11, -14, -10, -7, 51, -14,
	-11, -7, -7, 56, -14, 56, -6, -4, 54, -13,
	10, 10, -13, -10, 50, -10, -10, 26, 50, -13,
	50, 33, 57, -10, 51, 51, 51, -16, 57, -7,
	57, -7, -7, -7, -7, -7, -11, -12, -7, -7,
	-14, -7, -4, -10, 54, 54, -10, -7, -13, -15,
	10, -5, 30, -10, -7, -7, -13, -12, -12, -12,
	-7, 49, -7, 49, 51, -11, 51, 51, -7, 51,
	51, -7, 51, -10, -10, 51, -14, 28, 53, 50,
	51, -5, -10, 49, 49, -7, 51, -12, 51, -13,
	-10, -10, 10, -13, 51, -12, 51, 53, 10, -13,
	-10, 51, 51, -13, -13,
}
var yyDef = [...]int{

	1, -2, 2, 1, 0, 18, 0, 106, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 15, 16, 74,
	75, 9, 9, 0, 0, 11, 103, 104, 105, 70,
	1, 4, 17, 64, 65, 0, 9, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 19, -2, 24, 31, 9, 0, 101, 102, 106,
	0, 1, 0, 25, 9, 26, 27, 28, 29, 30,
	32, 0, -2, 33, 34, 0, 0, 37, 0, 12,
	9, 67, 0, 0, 0, 87, 3, 0, 22, 67,
	85, 88, 89, 90, 91, 92, 93, 94, 95, 96,
	97, 98, 99, 100, 0, 9, 0, 67, 72, 9,
	9, 0, 0, 73, 0, 6, -2, -2, 46, 0,
	106, 0, 0, 55, 0, 0, 0, 0, 13, 14,
	0, 0, 0, 0, 0, 10, 9, -2, 68, 9,
	0, 107, 9, 66, 9, -2, 20, 67, 107, -2,
	9, 67, 0, 41, 9, 63, -2, 8, 0, 62,
	47, 106, 51, 53, 9, 52, 54, 0, 67, 0,
	0, 9, 9, 0, 0, 0, 0, 71, 9, 0,
	9, 0, 0, 67, 0, 0, 9, 39, 0, 0,
	9, 0, 7, 50, 0, 0, 0, 67, 43, 44,
	106, 0, 0, 0, 67, 0, 42, 35, 36, 38,
	0, 76, 0, 78, 84, 9, 81, 83, 0, 84,
	80, 0, 82, 48, 49, 107, -2, 0, 0, 0,
	0, 61, 69, 77, 79, 0, 0, 40, 82, 60,
	0, 0, 0, 59, 86, 21, 0, 0, 0, 56,
	0, 0, 0, 58, 57,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 46, 3, 3,
	50, 51, 44, 42, 57, 43, 52, 45, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 58, 53,
	36, 54, 37, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 48, 3, 49, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 55, 3, 56,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 38, 39, 40, 41, 47,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	}
	goto yystack /* stack new state and value */
}
