// Code generated by goyacc -o paser.y.go -v parser.y.output parser.y. DO NOT EDIT.

//line parser.y:2
package main

import __yyfmt__ "fmt"

//line parser.y:2

//line parser.y:5
type yySymType struct {
	yys          int
	num          int
	str          string
	indent_level int
}

const NR = 57346
const EOF = 57347
const COMMENT = 57348
const BOOL = 57349
const NUMBER = 57350
const STRING = 57351
const IDENT = 57352
const DEF = 57353
const NEW = 57354
const ANY = 57355
const NONE = 57356
const SH = 57357
const ECHO = 57358
const AGENT = 57359
const LABEL = 57360
const STAGE = 57361
const NODE = 57362
const DIR = 57363
const SCRIPT = 57364
const ENVIRONMENT = 57365
const IMPORT = 57366
const IF = 57367
const ELSE = 57368
const FOR = 57369
const IN = 57370
const TRY = 57371
const CATCH = 57372
const OR = 57373
const AND = 57374
const EQ = 57375
const NE = 57376
const LE = 57377
const GE = 57378
const UNARY_OPERAND = 57379

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NR",
	"EOF",
	"COMMENT",
	"BOOL",
	"NUMBER",
	"STRING",
	"IDENT",
	"DEF",
	"NEW",
	"ANY",
	"NONE",
	"SH",
	"ECHO",
	"AGENT",
	"LABEL",
	"STAGE",
	"NODE",
	"DIR",
	"SCRIPT",
	"ENVIRONMENT",
	"IMPORT",
	"IF",
	"ELSE",
	"FOR",
	"IN",
	"TRY",
	"CATCH",
	"OR",
	"AND",
	"'<'",
	"'>'",
	"EQ",
	"NE",
	"LE",
	"GE",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"UNARY_OPERAND",
	"'['",
	"']'",
	"'('",
	"')'",
	"'.'",
	"';'",
	"'='",
	"'{'",
	"'}'",
	"','",
	"':'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:167

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 52,
	4, 21,
	5, 21,
	-2, 89,
	-1, 125,
	4, 7,
	46, 7,
	-2, 65,
	-1, 133,
	4, 7,
	48, 7,
	-2, 65,
	-1, 137,
	4, 7,
	48, 7,
	-2, 65,
	-1, 193,
	4, 7,
	48, 7,
	-2, 65,
}

const yyPrivate = 57344

const yyLast = 601

var yyAct = [...]int{

	126, 5, 20, 105, 5, 109, 56, 29, 53, 59,
	60, 61, 138, 107, 67, 32, 74, 159, 65, 68,
	141, 103, 103, 77, 1, 79, 173, 172, 31, 56,
	56, 5, 140, 62, 63, 66, 82, 58, 25, 85,
	86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
	96, 97, 54, 162, 99, 80, 100, 102, 98, 5,
	81, 25, 123, 18, 64, 18, 18, 108, 71, 70,
	119, 120, 58, 121, 58, 75, 76, 209, 125, 127,
	36, 177, 37, 104, 117, 196, 133, 153, 124, 130,
	83, 72, 69, 18, 25, 25, 132, 131, 195, 134,
	25, 194, 207, 25, 137, 204, 73, 25, 108, 101,
	25, 143, 148, 150, 151, 152, 19, 147, 25, 203,
	142, 18, 154, 41, 40, 42, 43, 44, 122, 118,
	158, 36, 176, 37, 42, 43, 44, 33, 199, 190,
	36, 25, 37, 108, 189, 171, 170, 187, 166, 25,
	77, 186, 145, 135, 184, 128, 84, 139, 175, 78,
	183, 28, 26, 27, 57, 51, 23, 106, 34, 118,
	118, 25, 17, 191, 192, 2, 185, 193, 160, 161,
	0, 0, 197, 182, 163, 3, 164, 165, 30, 167,
	0, 168, 169, 0, 24, 0, 202, 0, 0, 21,
	201, 22, 0, 174, 0, 118, 66, 0, 178, 179,
	180, 0, 208, 181, 0, 210, 28, 26, 27, 146,
	188, 23, 25, 0, 0, 28, 26, 27, 111, 110,
	23, 0, 0, 113, 112, 0, 0, 0, 0, 198,
	0, 0, 200, 114, 0, 115, 0, 116, 0, 24,
	0, 0, 205, 0, 21, 0, 149, 0, 24, 0,
	0, 66, 0, 21, 56, 22, 0, 0, 117, 0,
	66, 50, 49, 38, 39, 45, 46, 48, 47, 41,
	40, 42, 43, 44, 0, 0, 0, 36, 0, 37,
	25, 17, 66, 28, 26, 27, 7, 6, 23, 0,
	0, 8, 9, 11, 10, 14, 15, 16, 12, 13,
	4, 0, 50, 49, 38, 39, 45, 46, 48, 47,
	41, 40, 42, 43, 44, 0, 24, 0, 36, 0,
	37, 21, 144, 22, 50, 49, 38, 39, 45, 46,
	48, 47, 41, 40, 42, 43, 44, 0, 0, 0,
	36, 0, 37, 0, 35, 50, 49, 38, 39, 45,
	46, 48, 47, 41, 40, 42, 43, 44, 0, 0,
	0, 36, 206, 37, 50, 49, 38, 39, 45, 46,
	48, 47, 41, 40, 42, 43, 44, 0, 0, 0,
	36, 157, 37, 50, 49, 38, 39, 45, 46, 48,
	47, 41, 40, 42, 43, 44, 0, 0, 0, 36,
	156, 37, 50, 49, 38, 39, 45, 46, 48, 47,
	41, 40, 42, 43, 44, 0, 0, 0, 36, 155,
	37, 50, 49, 38, 39, 45, 46, 48, 47, 41,
	40, 42, 43, 44, 0, 0, 0, 36, 136, 37,
	50, 49, 38, 39, 45, 46, 48, 47, 41, 40,
	42, 43, 44, 0, 0, 0, 36, 129, 37, 28,
	26, 52, 57, 0, 23, 50, 49, 38, 39, 45,
	46, 48, 47, 41, 40, 42, 43, 44, 0, 0,
	0, 36, 0, 37, 0, 0, 0, 0, 0, 0,
	0, 0, 24, 0, 0, 0, 0, 21, 0, 55,
	0, 0, 0, 0, 58, 0, 0, 56, 49, 38,
	39, 45, 46, 48, 47, 41, 40, 42, 43, 44,
	0, 0, 0, 36, 0, 37, 38, 39, 45, 46,
	48, 47, 41, 40, 42, 43, 44, 0, 0, 0,
	36, 25, 37, 0, 28, 26, 27, 57, 0, 23,
	28, 26, 27, 57, 0, 23, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 24, 0, 0,
	0, 0, 21, 24, 22, 0, 0, 0, 21, 0,
	22,
}
var yyPact = [...]int{

	286, -1000, 167, 286, 127, 303, 155, 462, 553, 553,
	553, 20, -17, 154, 45, 22, 44, -1000, 102, -1000,
	-38, -1000, 553, 149, 553, -1000, -1000, -1000, -1000, -1000,
	286, -1000, -1000, 11, -1000, 553, -1000, 146, 553, 553,
	553, 553, 553, 553, 553, 553, 553, 553, 553, 553,
	553, 7, -1000, 444, -1000, 553, 553, -26, 286, 444,
	444, 444, -1000, -1000, -1000, -1000, 218, 444, -1000, 553,
	553, -1000, 553, -1000, -1000, 547, 145, 419, 42, 33,
	-1000, 127, 444, 547, -1000, 84, 84, 93, 93, 33,
	33, 33, 84, 84, 84, 84, 503, 486, 553, -1000,
	400, 547, 444, -1000, -21, -33, 34, 218, 281, -1000,
	142, 209, 553, 553, 553, 40, -17, -1000, 102, 381,
	362, 343, 145, 102, -37, -38, 444, -38, -49, -1000,
	-1000, -1000, -37, -38, 444, 547, -15, -38, -37, 547,
	-1000, -1000, 218, -1000, 553, -24, -25, -1000, 444, 553,
	444, 444, 240, 122, 51, -15, -15, -15, -1000, -1000,
	137, 114, 106, 547, 103, 99, -37, -1000, 96, 91,
	-1000, 444, 553, 553, 547, 75, 70, 38, -1000, -1000,
	-1000, 547, -1000, -1000, -1000, -37, -1000, -1000, 90, -15,
	-1000, 444, 444, -38, -17, 553, 109, 444, 57, -15,
	-1000, -1000, 324, 92, -1000, -1000, -17, 29, -1000, -17,
	-1000,
}
var yyPgo = [...]int{

	0, 24, 175, 185, 3, 167, 13, 53, 62, 15,
	0, 12, 52, 5, 2, 7, 116,
}
var yyR1 = [...]int{

	0, 1, 1, 1, 4, 4, 4, 7, 7, 8,
	8, 6, 6, 3, 3, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 12,
	5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
	5, 5, 5, 5, 13, 9, 9, 9, 11, 11,
	11, 14, 14, 15, 10, 10, 10, 10, 10, 10,
	10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
	10, 10, 10, 10, 10, 10, 10, 10, 16, 16,
	16, 16, 16,
}
var yyR2 = [...]int{

	0, 0, 3, 2, 0, 3, 2, 0, 2, 1,
	2, 1, 1, 1, 1, 2, 1, 2, 4, 8,
	3, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 5, 5, 2, 5, 5, 7, 3,
	1, 1, 2, 4, 4, 3, 2, 2, 2, 2,
	3, 5, 7, 8, 3, 1, 1, 3, 0, 1,
	4, 1, 4, 3, 1, 1, 5, 5, 6, 6,
	6, 5, 3, 7, 2, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 1, 1,
	1, 1, 3,
}
var yyChk = [...]int{

	-1000, -1, -2, -3, 24, -10, 11, 10, 15, 16,
	18, 17, 22, 23, 19, 20, 21, 5, -8, -16,
	-14, 45, 47, 12, 40, 4, 8, 9, 7, -15,
	-3, -1, -9, 10, 41, 51, 47, 49, 33, 34,
	40, 39, 41, 42, 43, 35, 36, 38, 37, 32,
	31, 10, 9, -10, -12, 47, 55, 10, 52, -10,
	-10, -10, 13, 14, -12, -13, 52, -10, -13, 47,
	47, -12, 47, 4, 54, -7, -7, -10, 10, -10,
	-1, 49, -10, -7, 10, -10, -10, -10, -10, -10,
	-10, -10, -10, -10, -10, -10, -10, -10, 51, 47,
	-10, -7, -10, 47, -1, -4, -5, -6, -10, -13,
	11, 10, 16, 15, 25, 27, 29, 50, -8, -10,
	-10, -10, -7, -8, -11, -14, -10, -14, 10, 48,
	47, -9, -11, -14, -10, -7, 48, -14, -11, -7,
	53, 53, -6, -4, 51, 10, 10, -13, -10, 47,
	-10, -10, -10, 47, -13, 48, 48, 48, -15, 54,
	-7, -7, -7, -7, -7, -7, -11, -12, -7, -7,
	-4, -10, 51, 51, -7, -13, 10, 30, -12, -12,
	-12, -7, 46, 46, 48, -11, 48, 48, -7, 48,
	48, -10, -10, -14, 26, 28, 47, -10, -7, 48,
	-12, -13, -10, 10, 48, -12, 48, 10, -13, 48,
	-13,
}
var yyDef = [...]int{

	1, -2, 0, 1, 0, 16, 0, 91, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 13, 14, 64,
	65, 7, 7, 0, 0, 9, 88, 89, 90, 61,
	1, 3, 15, 55, 56, 0, 7, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 17, -2, 22, 29, 7, 0, 91, 1, 23,
	24, 25, 26, 27, 28, 30, 4, 31, 32, 0,
	0, 35, 0, 10, 7, 58, 0, 0, 0, 74,
	2, 0, 20, 58, 72, 75, 76, 77, 78, 79,
	80, 81, 82, 83, 84, 85, 86, 87, 0, 7,
	0, 58, 63, 7, 0, 0, 0, 4, 40, 41,
	0, 91, 0, 0, 0, 0, 0, 11, 12, 0,
	0, 0, 0, 8, 7, -2, 59, 7, 0, 92,
	7, 57, 7, -2, 18, 58, 92, -2, 7, 58,
	39, 54, 4, 6, 0, 42, 91, 46, 48, 7,
	47, 49, 0, 0, 0, 0, 0, 0, 62, 7,
	0, 0, 0, 58, 0, 0, 7, 37, 0, 0,
	5, 45, 0, 0, 58, 50, 0, 0, 33, 34,
	36, 0, 66, 67, 71, 7, 69, 70, 0, 71,
	68, 43, 44, -2, 0, 0, 0, 60, 0, 0,
	38, 51, 0, 0, 73, 19, 0, 0, 52, 0,
	53,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 43, 3, 3,
	47, 48, 41, 39, 54, 40, 49, 42, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 55, 50,
	33, 51, 34, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 45, 3, 46, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 52, 3, 53,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 35, 36, 37, 38, 44,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	}
	goto yystack /* stack new state and value */
}
