// Code generated by goyacc -o paser.y.go -v parser.y.output parser.y. DO NOT EDIT.

//line parser.y:2
package main

import __yyfmt__ "fmt"

//line parser.y:2
// import "fmt"

//line parser.y:6
type yySymType struct {
	yys          int
	num          int
	str          string
	indent_level int
}

const NR = 57346
const EOF = 57347
const COMMENT = 57348
const BOOL = 57349
const NUMBER = 57350
const STRING = 57351
const IDENT = 57352
const DEF = 57353
const NEW = 57354
const ANY = 57355
const NONE = 57356
const SH = 57357
const ECHO = 57358
const AGENT = 57359
const LABEL = 57360
const STAGE = 57361
const NODE = 57362
const DIR = 57363
const SCRIPT = 57364
const ENVIRONMENT = 57365
const IMPORT = 57366
const IF = 57367
const ELSE = 57368
const OR = 57369
const AND = 57370
const EQ = 57371
const NE = 57372
const LE = 57373
const GE = 57374
const UNARY_OPERAND = 57375

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NR",
	"EOF",
	"COMMENT",
	"BOOL",
	"NUMBER",
	"STRING",
	"IDENT",
	"DEF",
	"NEW",
	"ANY",
	"NONE",
	"SH",
	"ECHO",
	"AGENT",
	"LABEL",
	"STAGE",
	"NODE",
	"DIR",
	"SCRIPT",
	"ENVIRONMENT",
	"IMPORT",
	"IF",
	"ELSE",
	"OR",
	"AND",
	"'<'",
	"'>'",
	"EQ",
	"NE",
	"LE",
	"GE",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"UNARY_OPERAND",
	"'['",
	"']'",
	"'('",
	"')'",
	"'.'",
	"';'",
	"'{'",
	"'}'",
	"'='",
	"','",
	"':'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:166

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 48,
	4, 17,
	5, 17,
	-2, 79,
	-1, 118,
	42, 7,
	-2, 55,
}

const yyPrivate = 57344

const yyLast = 492

var yyAct = [...]int{

	5, 102, 71, 106, 104, 31, 28, 49, 55, 56,
	57, 100, 52, 63, 160, 61, 64, 50, 24, 52,
	123, 98, 74, 128, 76, 24, 70, 19, 60, 123,
	153, 152, 67, 130, 81, 129, 83, 84, 85, 86,
	87, 88, 89, 90, 91, 92, 93, 94, 95, 73,
	135, 127, 96, 99, 125, 79, 17, 70, 1, 124,
	70, 80, 30, 105, 70, 123, 113, 114, 119, 115,
	62, 123, 81, 116, 70, 58, 59, 72, 66, 97,
	54, 78, 54, 100, 122, 121, 24, 62, 77, 68,
	33, 52, 34, 117, 65, 27, 25, 48, 53, 118,
	22, 81, 159, 158, 164, 105, 132, 143, 131, 54,
	137, 138, 136, 101, 134, 32, 82, 75, 24, 112,
	144, 145, 81, 142, 23, 69, 147, 72, 111, 20,
	18, 51, 105, 150, 151, 54, 24, 16, 3, 52,
	103, 29, 154, 146, 148, 149, 2, 0, 161, 0,
	0, 0, 0, 162, 163, 0, 0, 155, 156, 157,
	112, 112, 38, 37, 39, 40, 41, 0, 165, 0,
	33, 0, 34, 0, 72, 72, 39, 40, 41, 0,
	72, 0, 33, 0, 34, 0, 0, 0, 112, 47,
	46, 35, 36, 42, 43, 45, 44, 38, 37, 39,
	40, 41, 0, 0, 0, 33, 0, 34, 0, 0,
	0, 133, 47, 46, 35, 36, 42, 43, 45, 44,
	38, 37, 39, 40, 41, 0, 0, 0, 33, 0,
	34, 0, 62, 24, 16, 0, 27, 25, 26, 6,
	0, 22, 0, 0, 7, 8, 10, 9, 13, 14,
	15, 11, 12, 4, 24, 0, 0, 27, 25, 26,
	108, 107, 22, 0, 0, 23, 109, 0, 0, 0,
	20, 0, 21, 0, 0, 110, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 23, 0, 0, 0,
	0, 20, 0, 21, 0, 0, 111, 62, 47, 46,
	35, 36, 42, 43, 45, 44, 38, 37, 39, 40,
	41, 0, 0, 0, 33, 141, 34, 47, 46, 35,
	36, 42, 43, 45, 44, 38, 37, 39, 40, 41,
	0, 0, 0, 33, 140, 34, 47, 46, 35, 36,
	42, 43, 45, 44, 38, 37, 39, 40, 41, 0,
	0, 0, 33, 139, 34, 47, 46, 35, 36, 42,
	43, 45, 44, 38, 37, 39, 40, 41, 0, 0,
	0, 33, 126, 34, 47, 46, 35, 36, 42, 43,
	45, 44, 38, 37, 39, 40, 41, 0, 0, 0,
	33, 120, 34, 47, 46, 35, 36, 42, 43, 45,
	44, 38, 37, 39, 40, 41, 0, 0, 0, 33,
	0, 34, 46, 35, 36, 42, 43, 45, 44, 38,
	37, 39, 40, 41, 0, 0, 0, 33, 0, 34,
	35, 36, 42, 43, 45, 44, 38, 37, 39, 40,
	41, 0, 0, 0, 33, 0, 34, 27, 25, 26,
	53, 0, 22, 0, 0, 27, 25, 26, 53, 0,
	22, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 23, 0, 0, 0,
	0, 20, 0, 21, 23, 0, 0, 62, 0, 20,
	0, 21,
}
var yyPact = [...]int{

	229, -1000, 132, 229, 105, 366, 88, 448, 448, 448,
	62, 23, 440, 51, 35, 46, -1000, 121, -1000, -24,
	114, 448, 107, 448, -1000, -1000, -1000, -1000, -1000, 229,
	-1000, -1000, 36, 448, 106, 448, 448, 448, 448, 448,
	448, 448, 448, 448, 448, 448, 448, 448, -1000, 366,
	-1000, 448, 448, -32, 229, 366, 366, 366, -1000, -1000,
	-1000, -1000, 250, 366, -1000, 448, 448, -1000, 448, -1000,
	114, 448, 121, 24, 347, 42, 47, -1000, 105, 15,
	10, 366, -1000, 127, 127, 139, 139, 47, 47, 47,
	127, 127, 127, 127, 401, 384, 328, 7, -21, 366,
	448, -13, -15, 82, 250, 162, -1000, 104, 40, 448,
	448, -1000, 121, 309, 290, 271, 97, 21, 14, -1000,
	-1000, 448, -1000, 114, -1000, -1000, 33, 33, -1000, -1000,
	-1000, 250, -1000, 448, -18, -19, -1000, 366, 185, 33,
	33, 33, -1000, -39, 61, 60, -30, 448, -1000, -1000,
	-1000, 366, 448, 448, 78, -1000, -1000, -1000, -1000, -1000,
	-1000, 366, 366, 366, 23, -1000,
}
var yyPgo = [...]int{

	0, 58, 146, 138, 1, 140, 4, 2, 56, 5,
	0, 17, 3, 27, 21, 6, 130,
}
var yyR1 = [...]int{

	0, 1, 1, 1, 4, 4, 4, 7, 7, 8,
	8, 6, 6, 3, 3, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 11, 5, 5, 5, 5,
	5, 5, 5, 5, 5, 12, 9, 9, 14, 14,
	14, 13, 13, 15, 10, 10, 10, 10, 10, 10,
	10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
	10, 10, 10, 10, 10, 10, 10, 10, 16, 16,
	16, 16, 16,
}
var yyR2 = [...]int{

	0, 0, 3, 2, 0, 3, 2, 0, 1, 1,
	2, 1, 1, 1, 1, 2, 1, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 5,
	5, 2, 5, 5, 5, 3, 1, 1, 4, 4,
	3, 2, 2, 3, 5, 3, 1, 3, 0, 1,
	4, 1, 4, 3, 1, 1, 5, 5, 4, 4,
	4, 3, 3, 5, 2, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 1, 1,
	1, 1, 3,
}
var yyChk = [...]int{

	-1000, -1, -2, -3, 24, -10, 10, 15, 16, 18,
	17, 22, 23, 19, 20, 21, 5, -8, -16, -13,
	41, 43, 12, 36, 4, 8, 9, 7, -15, -3,
	-1, -9, 10, 43, 45, 29, 30, 36, 35, 37,
	38, 39, 31, 32, 34, 33, 28, 27, 9, -10,
	-11, 43, 51, 10, 47, -10, -10, -10, 13, 14,
	-11, -12, 47, -10, -12, 43, 43, -11, 43, 4,
	50, -7, -8, -13, -10, 10, -10, -1, 45, -14,
	-13, -10, 10, -10, -10, -10, -10, -10, -10, -10,
	-10, -10, -10, -10, -10, -10, -10, -13, -14, -10,
	43, -1, -4, -5, -6, -10, -12, 11, 10, 16,
	25, 46, -8, -10, -10, -10, -7, -14, -13, 44,
	44, 43, -9, 50, 44, 44, 44, 44, 44, 48,
	48, -6, -4, 49, 10, 10, -12, -10, -10, 44,
	44, 44, -15, 10, -7, -7, -14, -7, -11, -11,
	-4, -10, 49, 49, -12, -11, -11, -11, 42, 42,
	44, -10, -10, -10, 26, -12,
}
var yyDef = [...]int{

	1, -2, 0, 1, 0, 16, 81, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 13, 14, 54, 55,
	7, 0, 0, 0, 9, 78, 79, 80, 51, 1,
	3, 15, 46, 48, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, -2, 18,
	25, 48, 0, 81, 1, 19, 20, 21, 22, 23,
	24, 26, 4, 27, 28, 0, 0, 31, 0, 10,
	7, 48, 8, 55, 0, 0, 64, 2, 0, 0,
	55, 49, 62, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 49, 55, 0, 53,
	48, 0, 0, 0, 4, 36, 37, 0, 81, 0,
	0, 11, 12, 0, 0, 0, 0, 7, -2, 61,
	82, 48, 47, 7, 59, 60, 82, 61, 58, 35,
	45, 4, 6, 0, 0, 0, 41, 42, 0, 0,
	0, 0, 52, 0, 0, 0, 0, 0, 33, 34,
	5, 40, 0, 0, 43, 29, 30, 32, 56, 57,
	63, 50, 38, 39, 0, 44,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 39, 3, 3,
	43, 44, 37, 35, 50, 36, 45, 38, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 51, 46,
	29, 49, 30, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 41, 3, 42, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 47, 3, 48,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 31, 32, 33,
	34, 40,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	}
	goto yystack /* stack new state and value */
}
